name: Test and upload coverage

on:
  push:
    branches : [main]
  pull_request:
    branches : [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'

      - name: Build with Gradle
        uses: gradle/actions@v4.2.1

      - name: Install dependencies and build
        run: |
          ./gradlew clean build

      - name: Run unit tests with coverage
        run: |
          ./gradlew testDebugUnitTest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
